name: Build, Test, and Push QR Code Generator Docker Image

on:
push:
branches: [ main ]
pull_request:
branches: [ main ]

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.12"

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  - name: Run quick functional test
    run: |
      echo "Running QR code generation test..."
      python main.py --url "https://example.com"
      test -f qr_codes/*.png && echo "QR code successfully generated."

  - name: Lint Python files
    run: |
      pip install flake8
      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true

  - name: Build Docker image
    run: docker build -t qr-code-generator-app .

  - name: Log in to DockerHub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  - name: Tag Docker image
    run: docker tag qr-code-generator-app ${{ secrets.DOCKERHUB_USERNAME }}/qr-code-generator-app:latest

  - name: Push Docker image to DockerHub
    run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/qr-code-generator-app:latest
```
